apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fwd
  annotations:
    ingress.kubernetes.io/protocol: h2c
spec:
  rules:
  - host: ingress.dev.kuharski-koticek.com
    http:
      paths:
      - backend:
          serviceName: fwd
          servicePort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: fwd
spec:
  type: ClusterIP
  selector:
    app: fwd
  ports:
    - protocol: TCP
      port: 50051
---
apiVersion: v1
kind: Pod
metadata:
  name: fwd
  labels:
    app: fwd
spec:
  containers:
    - name: fwd
      image: alpine
      command: ['sleep', 'infinity']  # need to cp and run server manually as there is no image yet
      ports:
        - name: grpc
          containerPort: 50051
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    app: web
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80

